spring:
  profiles:
    active: alpha
  redis:
    host: localhost
    port: 6379
#  개발 할 때 static 파일을 재시작 하지 않아도 불러올 수 있게 된다.
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
    template-loader-path: classpath:/templates
    suffix: .ftl
#  alpha 서버용 환경 설정
#  profiles:
#    active: alpha
#  redis:
#    host: localhost
#    port: redis가 설치된 서버 포트
