spring:
  profiles:
    active: local
  #  개발 할 때 static 파일을 재시작 하지 않아도 불러올 수 있게 된다.
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
    template-loader-path: classpath:/templates
    suffix: .ftl
---
spring:
  config:
    activate:
      on-profile: local
  redis:
    host: localhost
    port: 6380
---
#  alpha 서버용 환경 설정
spring:
  config:
    activate:
      on-profile: alpha
  redis:
    host: localhost
    port: 6379
